#!/run/current-system/sw/bin/bash
## Script to move some files and generate hardware config

set -eu
set -x

mv ~/NixOS-Hyprland ¨/nixos-config
cd ~/nixos-config

cp -r ~/nixos-config/bin ~

mkdir ~/Bilder
mkdir ~/Bilder/wallpaper
cp ~/nixos-config/blue-mountain.jpg ~/Bilder/wallpaper

sudo nixos-generate-config --dir /tmp/nixos-config
sudo mv /tmp/nixos-config/hardware-configuration.nix ~/nixos-config/system

cat ~/nixos-config/system/hardware-configuration.nix
