#!/run/current-system/sw/bin/bash
## Script to move some files and generate hardware config

set -eu
set -x

cd $HOME/nixos-config

cp -r $HOME/nixos-config/bin $HOME
cp $HOME/nixos-config/blue-mountain.jpg $HOME/Bilder/wallpaper

sudo nixos-generate-config --dir /tmp/nixos-config
mv /tmp/nixos-config/hardware-configuration.nix $HOME/nixos-config/system

cat $HOME/nixos-config/system/hardware-configuration.nix
