[
  "XCURSOR_SIZE,24"
  "HYPRCURSOR_SIZE,24"
  "HYPRCURSOR_THEME,Bibata-Modern-Classic"
  "XCURSOR_THEME,Bibata-Modern-Classic"
  "GTK_THEME,Adwaita:dark"
  "QT_QPA_PLATFORM,wayland:xcb"
  "GDK_BACKEND,wayland,x11"
]
